### ISSUE TITLE
can you make one that able to connect to channel 149?

### ISSUE THREAD

**Issue by floxflux** [chris1111/WIFI-USB-Adapter#1]
can you make one that able to connect to channel 149?

**Comment by chris1111** [comment]
> can you make one that able to connect to channel 149?


what is channel 149

**Comment by floxflux** [comment]
The channel of the wifi radio. Currently i can only connect to channel 36 on a mac. I wish to be able to connect on channel 149. Im using linksys wusb6300. I currently able to connect to channel 149 if im using windows, but using wusb6400 driver.

**Comment by chris1111** [comment]
> The channel of the wifi radio. Currently i can only connect to channel 36 on a mac. I wish to be able to connect on channel 149. Im using linksys wusb6300. I currently able to connect to channel 149 if im using windows, but using wusb6400 driver.

Take a look here ?
http://www.tomshardware.com/answers/id-3643741/connect-5gz-network-realtech-rtl8811au-lan-802-11ac-usb.html#lastAnswer
