### ISSUE TITLE
realtek repo duplicate?

### ISSUE THREAD

**Issue by htpcrig** [chris1111/WIFI-USB-Adapter#2]
Hi Chris
You have 2 repo for your Realtek driver (non-clover install).
This and https://github.com/chris1111/Wireless-USB-Adapter
which is which?

**Comment by chris1111** [comment]
> Hi Chris
> You have 2 repo for your Realtek driver (non-clover install).
> This and https://github.com/chris1111/Wireless-USB-Adapter
> which is which?

This is different drivers
issue is closed
